module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#614ea1',
        'primary-dim': '#005498',
        'surface-dim': '#d3dbdf',
        'outline-variant': '#acb3b7',
        'on-tertiary': '#eeffd7',
        'inverse-surface': '#0b0f10',
        'primary-fixed': '#9ac3ff',
        'tertiary-container': '#a4fd4c',
        'on-primary': '#f8f8ff',
        'tertiary-dim': '#335e00',
        'on-surface-variant': '#596063',
        'tertiary': '#3a6b00',
        'surface-variant': '#dde3e7',
        'on-primary-fixed': '#00284e',
        'tertiary-fixed-dim': '#96ee3e',
        'surface-container-highest': '#dde3e7',
        'primary': '#0060ad',
        'on-surface': '#2d3337',
        'background': '#f7f9fb',
        'on-tertiary-container': '#335e00',
        'secondary-container': '#e7deff',
        'surface-bright': '#f7f9fb',
        'on-secondary-fixed': '#443083',
        'error-container': '#f56965',
        'surface-container-high': '#e3e9ec',
        'surface-tint': '#0060ad',
        'on-secondary-container': '#574497',
        'surface-container-lowest': '#ffffff',
        'surface': '#f7f9fb',
        'surface-container': '#eaeef1',
        'on-background': '#2d3337',
        'inverse-primary': '#68abff',
        'tertiary-fixed': '#a4fd4c',
        'on-secondary': '#fdf7ff',
        'inverse-on-surface': '#9a9d9f',
        'on-primary-fixed-variant': '#004681',
        'on-error': '#fff7f6',
        'on-error-container': '#65000b',
        'primary-container': '#9ac3ff',
        'outline': '#757c7f',
        'secondary-dim': '#584598',
        'primary-fixed-dim': '#7fb6ff',
        'on-tertiary-fixed-variant': '#396900',
        'surface-container-low': '#f1f4f6',
        'secondary-fixed': '#e7deff',
        'on-primary-container': '#003d71',
        'error': '#ac3434',
        'on-tertiary-fixed': '#274a00',
        'error-dim': '#70030f',
        'secondary-fixed-dim': '#dacdff',
        'secondary': '#6452a5',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
};

